xsrv: fix pwgen password generation - move random password generation to separate function - generate different passwords for each placeholder - fixes #407

diff --git a/xsrv b/xsrv
--- a/xsrv
+++ b/xsrv
@@ -128,6 +128,25 @@ function init_playbook() {
     echo "[xsrv] INFO: run $0 deploy to apply configuration now, or $0 help for more options"
 }
 
+function gen_random_passwords() {
+    host_vault_file="$1"
+    if ! command -v pwgen >/dev/null; then
+        echo "[xsrv] WARNING: pwgen not installed, unable to generate random passwords for $host_name. Please manually replace any values labeled CHANGEME!"
+        return
+    fi
+
+    echo "[xsrv] INFO: generating random passwords for $host_name"
+    randomized_vault=$(while read -r line; do
+        if echo "$line" | grep -E 'CHANGEME[0-9]+' 2>&1 >/dev/null; then
+            num_char=$(echo "$line" | grep -oP '(?<=CHANGEME)[0-9]+(?=")')
+            echo "$line" | sed -E "s/CHANGEME[0-9]+/$(pwgen -s "$num_char" 1)/"
+        else
+            echo "$line"
+        fi
+    done < "$host_vault_file")
+    echo "$randomized_vault" > "$host_vault_file"
+}
+
 function init_host() {
     # add a new host to a playbook (from template files)
     check_playbook_exists
@@ -158,15 +177,7 @@ function init_host() {
     sed "s/my.example.org/$host_name/g" "$templates_dir/playbooks/xsrv/host_vars/my.example.org/my.example.org.yml" > "$host_vars_file"
     sed "s/my.example.org/$host_name/g" "$templates_dir/playbooks/xsrv/host_vars/my.example.org/my.example.org.vault.yml" > "$host_vault_file"
 
-    if command -v pwgen >/dev/null; then
-        echo "[xsrv] INFO: generating random passwords for $host_name"
-        for i in 20 250 40 12 106 64 43 30; do
-            random_password=$(pwgen -s "$i" 1);
-            sed -i "s/CHANGEME$i/$random_password/g" "$host_vault_file"
-        done
-    else
-        echo "[xsrv] WARNING: pwgen not installed, unable to generate random passwords for $host_name. Please manually replace any values labeled CHANGEME!"
-    fi
+    gen_random_passwords "$host_vault_file"
 
     read -r -p "[xsrv] Press ENTER to edit the playbook (enable/disable roles)"
     edit_playbook "$playbook_name"
@@ -273,6 +284,8 @@ function show_defaults() {
     fi
 }
 
+############################
+
 function _main() {
     echo "$ascii_banner"
     if [[ -z "$command" ]]; then echo "[xsrv] ERROR: no command provided"; echo "$usage"; exit 1; fi
@@ -296,7 +309,7 @@ function _main() {
 }
 
 
-############################"
+############################
 
 # Usage
 usage="
@@ -331,4 +344,5 @@ command="${1:-}"
 playbook_name="${2:-default}"
 host_name="${3:-}"
 ssh_args=""
+
 _main "$@"
