xsrv: init-vm: rename --dump option to --dumpxml, require output file as argument - doc: update help text - fix inconsistent info/error messages - --dump should still work - makefile: update test_init_vm test

diff --git a/xsrv b/xsrv
--- a/xsrv
+++ b/xsrv
@@ -359,8 +359,8 @@ function self_upgrade() {
 ########## LIBVIRT RELATED COMMANDS ##########
 
 function init_vm() {
-    INIT_VM_USAGE="$0 init-vm  --name VM_NAME [--template debian11-base] --ip VM_IP --netmask VM_NETMASK --gateway VM_GATEWAY [--ssh-port VM_SSH_PORT] [--sudo-user deploy] [--sudo-password VM_SUDO_PASSWORD] --ssh-pubkey 'ssh-rsa AAAAB...' [--root-password VM_ROOT_PASSWORD] [--disk-path /path/to/my.CHANGEME.org.qcow2] [--memory 1024] [--vcpus NUM_CPU]
-        EXAMPLE: $0 init-vm --template debian11-base --name my.CHANGEME.org --ip 10.0.0.223 --netmask 24 --gateway 10.0.0.1 --sudo-user deploy --sudo-password CHANGEME --ssh-pubkey 'ssh-rsa AAAAB...' --root-password CHANGEME --memory 3G --vcpus 4 [--dump]
+    INIT_VM_USAGE="$0 init-vm  --name VM_NAME [--template debian11-base] --ip VM_IP [--netmask 24] --gateway VM_GATEWAY [--ssh-port VM_SSH_PORT] [--sudo-user deploy] [--sudo-password VM_SUDO_PASSWORD] --ssh-pubkey 'ssh-rsa AAAAB...' [--root-password VM_ROOT_PASSWORD] [--disk-path /path/to/my.CHANGEME.org.qcow2] [--memory 1024] [--vcpus NUM_CPU]
+        EXAMPLE: $0 init-vm --template debian11-base --name my.CHANGEME.org --ip 10.0.0.223 --netmask 24 --gateway 10.0.0.1 --sudo-user deploy --sudo-password CHANGEME --ssh-pubkey 'ssh-rsa AAAAB...' --root-password CHANGEME --memory 3G --vcpus 4 [--dumpxml /path/to/libvirt/vm/definition.xml]
         Initialize a libvirt VM from a template, configure resources/users/SSH access, and start the VM.
         Requirements: openssh-client sshpass libvirt virtinst libvirt-daemon-system libguestfs-tools pwgen netcat-openbsd util-linux
         --template      name of the template to create the new VM from (default debian11-base)
@@ -375,10 +375,10 @@ function init_vm() {
         --disk-path     path to the qcow2 disk image to create (default: /var/lib/libvirt/images/VM_NAME.qcow2)
         --memory        VM memory with M or G suffix (default 1G)
         --vcpus         number of vCPUs (default: same value as the template)
-        --dump          display the VM XML definition after creation, for use with the nodiscc.xsrv.libvirt role
+        --dumpxml       write the VM XML definition to a file after creation
         "
     # parse command-line options
-    long_opts="help,template:,name:,ip:,netmask:,gateway:,ssh-port:,root-password:,sudo-user:,sudo-password:,ssh-pubkey:,disk-path:,memory:,vcpus:,dump"
+    long_opts="help,template:,name:,ip:,netmask:,gateway:,ssh-port:,root-password:,sudo-user:,sudo-password:,ssh-pubkey:,disk-path:,memory:,vcpus:,dumpxml:"
     GETOPT=$(getopt -o '' --longoptions "$long_opts" --name "[xsrv] ERROR" -- "$@")
     eval set -- "$GETOPT"
     # default values
@@ -413,14 +413,14 @@ function init_vm() {
             --disk-path) disk_path=$2; shift 2;;
             --memory) memory=$2; shift 2;;
             --vcpus) vcpus=$2; shift 2;;
-            --dump) dump=yes; shift;;
+            --dumpxml) dump=yes; dumpxml_file=$2; shift 2;;
             --) shift; break;;
             *) echo "[xsrv] ERROR: invalid option $1"; echo "USAGE: $INIT_VM_USAGE"; exit 1;;
         esac
     done
     # check mandatory options
-    for i in "$template" "$name" "$ip" "$gateway" "$sudo_user" "$ssh_pubkey"; do
-        if [[ -z "$i" ]]; then echo "[xsrv] ERROR: missing required option --$i"; echo "[xsrv] USAGE: $INIT_VM_USAGE"; exit 1; fi
+    for i in "$name" "$ip" "$gateway" "$sudo_user" "$ssh_pubkey"; do
+        if [[ -z "$i" ]]; then echo "[xsrv] ERROR: missing required option"; echo "[xsrv] USAGE: $INIT_VM_USAGE"; exit 1; fi
     done
     # build /etc/network/interfaces for the target system 
     cat > ./libvirt-clone-interfaces.txt << EOF
@@ -471,7 +471,7 @@ EOF
     fi
     echo "[xsrv] INFO: starting VM $name..."
     virsh start "$name"
-    echo "[xsrv] INFO: waiting $name ssh server to start accepting connections..."
+    echo "[xsrv] INFO: waiting for $name SSH server to start accepting connections..."
     until nc -w 1 "$name" "$ssh_port"; do sleep 1; done
     echo "[xsrv] INFO: adding $name ssh server's hostkey to known_hosts file..."
     ssh-keyscan -H "$name" 2>/dev/null >> ~/.ssh/known_hosts
@@ -484,10 +484,10 @@ EOF
     rm ./libvirt-clone-interfaces.txt
 
     if [[ "$dump" == "yes" ]]; then
+        echo "[xsrv] INFO: dumping VM XML definition to $dumpxml_file"
         echo "[xsrv] INFO: You may now start managing this VM using th nodiscc.xsrv.libvirt_role."
         echo -e "libvirt_vms:\\n  - name: $name\\n    xml_file: '{{ playbook_dir }}/data/libvirt/$name.xml'"
-        echo "[xsrv] INFO: $projects_dir/default/data/libvirt/$name.xml:"
-        virsh dumpxml "$name"
+        virsh dumpxml "$name" > "$dumpxml_file"
     fi
 }
 
